In [1]:

import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('weatherAUS.csv')
X = dataset.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
Y = dataset.iloc[:,-1].values


In [3]:
Z = dataset.iloc[:,[4,7,8,9,10,11,12,15,16,17,18,19,20,21]].values

In [4]:
print(Z)

[[0.6 'W' 44.0 ... 16.9 21.8 'No']
 [0.0 'WNW' 44.0 ... 17.2 24.3 'No']
 [0.0 'WSW' 46.0 ... 21.0 23.2 'No']
 ...
 [0.0 'N' 37.0 ... 12.5 26.1 'No']
 [0.0 'SE' 28.0 ... 15.1 26.0 'No']
 [0.0 nan nan ... 15.0 20.9 'No']]


In [5]:
dataset.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  

[5 rows x 23 columns]

In [6]:
print(X)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 nan ... 15.0 20.9 'No']]


In [7]:
print(Y)

['No' 'No' 'No' ... 'No' 'No' nan]


In [8]:
Y = Y.reshape(-1,1)


In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
X = imputer.fit_transform(X)
Y = imputer.fit_transform(Y)

In [10]:
print(X)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 20.0 ... 15.0 20.9 'No']]


In [11]:
print(Y)


[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


In [12]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
X[:,0] = le1.fit_transform(X[:,0])
le2 = LabelEncoder()
X[:,4] = le2.fit_transform(X[:,4])
le3 = LabelEncoder()
X[:,6] = le3.fit_transform(X[:,6])
le4 = LabelEncoder()
X[:,7] = le4.fit_transform(X[:,7])
le5 = LabelEncoder()
X[:,-1] = le5.fit_transform(X[:,-1])
le6 = LabelEncoder()
Y[:,-1] = le6.fit_transform(Y[:,-1])

In [13]:
print(X)

[[2 13.4 22.9 ... 16.9 21.8 0]
 [2 7.4 25.1 ... 17.2 24.3 0]
 [2 12.9 25.7 ... 21.0 23.2 0]
 ...
 [41 5.4 26.9 ... 12.5 26.1 0]
 [41 7.8 27.0 ... 15.1 26.0 0]
 [41 14.9 20.0 ... 15.0 20.9 0]]


In [14]:
print(Y)


[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [15]:
Y = np.array(Y,dtype=float)
print(Y)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [17]:
print(X)


[[-1.53166617  0.19132753 -0.04135977 ... -0.01407077  0.02310362
  -0.52979545]
 [-1.53166617 -0.75105231  0.26874452 ...  0.03244663  0.387799
  -0.52979545]
 [-1.53166617  0.11279588  0.35331842 ...  0.62166712  0.22733303
  -0.52979545]
 ...
 [ 1.20928479 -1.06517892  0.52246622 ... -0.69632607  0.65037966
  -0.52979545]
 [ 1.20928479 -0.68822699  0.53656187 ... -0.29317521  0.63579185
  -0.52979545]
 [ 1.20928479  0.42692249 -0.45013361 ... -0.30868102 -0.10818671
  -0.52979545]]


In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [19]:
print(X_train)

[[ 0.22535368  1.03946939  0.07140543 ...  0.68369032  0.08145488
  -0.52979545]
 [ 1.42012717 -0.45263203  0.11369237 ... -0.41722163  0.22733303
  -0.52979545]
 [ 0.50647685 -0.20133073 -0.14002932 ... -0.06058818 -0.02065982
   1.88752093]
 ...
 [ 1.0687232   0.75675544  0.93124006 ...  1.10234698  1.07342629
  -0.52979545]
 [ 0.57675765 -0.04426743 -0.16822062 ...  0.01694083 -0.28324049
   1.88752093]
 [ 1.63096955 -0.0285611  -0.91529006 ... -0.35519842 -0.76463838
  -0.52979545]]


In [20]:
print(Y_train)

[[1.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [21]:

from sklearn.ensemble import RandomForestClassifier
import joblib

# Assuming you have X_train and Y_train as your training data
# Train the model
classifier = RandomForestClassifier(n_estimators=100, random_state=0)
classifier.fit(X_train,Y_train)

# Save the model
joblib.dump(classifier, 'random_forest_model.pkl')


C:\Users\prath\AIprojects\env\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


['random_forest_model.pkl']

In [22]:
classifier.score(X_train,Y_train)

0.9999312525780283

In [23]:
y_pred = le6.inverse_transform(np.array(classifier.predict(X_test),dtype=int))
Y_test = le6.inverse_transform(np.array(Y_test,dtype=int))

C:\Users\prath\AIprojects\env\Lib\site-packages\sklearn\preprocessing\_label.py:153: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [24]:
print(y_pred)

['No' 'No' 'No' ... 'No' 'No' 'No']


In [25]:
print(Y_test)

['Yes' 'Yes' 'No' ... 'Yes' 'No' 'No']


In [26]:
y_pred = y_pred.reshape(-1,1)
Y_test = Y_test.reshape(-1,1)

In [27]:
df = np.concatenate((Y_test,y_pred),axis=1)
dataframe = pd.DataFrame(df,columns=['Rain on Tommorrow','Predition of Rain'])

In [28]:
print(dataframe)

      Rain on Tommorrow Predition of Rain
0                   Yes                No
1                   Yes                No
2                    No                No
3                    No               Yes
4                    No                No
...                 ...               ...
29087                No               Yes
29088                No                No
29089               Yes                No
29090                No                No
29091                No                No

[29092 rows x 2 columns]


In [29]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

0.8521930427608965

In [30]:
# Taking the input data

In [31]:
from sklearn.preprocessing import LabelEncoder
import joblib

# Assuming you have categorical variables encoded in X
# Train the LabelEncoder
label_encoder = LabelEncoder()
X_categorical_encoded = label_encoder.fit_transform(X[:, 0])  # Assuming the location is in the first column

# Save the LabelEncoder
joblib.dump(label_encoder, 'label_encoder.pkl')


['label_encoder.pkl']

In [32]:
import numpy as np
import pandas as pd
import joblib

# Load the dataset
dataset = pd.read_csv('weatherAUS.csv')

# Extract features and target variable
X = dataset[['Location', 'MinTemp', 'MaxTemp', 'Humidity9am', 'Humidity3pm','Rainfall', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm', 'WindSpeed9am',
                      'WindSpeed3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am', 'Temp3pm', 'RainToday']]
Y = dataset['RainTomorrow']

# Identify remaining features and their most common values
remaining_features = ['Rainfall', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm', 'WindSpeed9am',
                      'WindSpeed3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'MinTemp', 'MaxTemp', 'RainToday']
default_values = {feature: dataset[feature].mode()[0] for feature in remaining_features}

# Function to preprocess user input
def preprocess_input(location, Temp_9am, Temp_3pm, humidity_9am, humidity_3pm, **kwargs):
    # Create a DataFrame from the user input
    input_data = pd.DataFrame({'Location': [location],
                               'Temp9am': [Temp_9am],
                               'Temp3pm': [Temp_3pm],
                               'Humidity9am': [humidity_9am],
                               'Humidity3pm': [humidity_3pm]})
    
    # Fill in default values for remaining features
    for feature, default_value in default_values.items():
        input_data[feature] = kwargs.get(feature, default_value)
    
    # One-hot encode categorical variables
    for cat_feature in ['Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainToday']:
        input_data = pd.get_dummies(input_data, columns=[cat_feature], drop_first=True)
    
    # Ensure all columns are present and in the correct order
    for col in X.columns:
        if col not in input_data.columns:
            input_data[col] = 0
    
    print("Shape of input data after preprocessing:", input_data.shape)
    return input_data[X.columns].values

# Preprocess user input
def predict_rain(location, Temp_9am, Temp_3pm, humidity_9am, humidity_3pm, **kwargs):
    input_data = preprocess_input(location, Temp_9am, Temp_3pm, humidity_9am, humidity_3pm, **kwargs)

    # Load saved model
    classifier = joblib.load('random_forest_model.pkl')

    # Make prediction
    prediction = classifier.predict(input_data)

    return prediction[0]

# Example usage:
location = input("Enter Location: ")
Temp_9am = float(input("Enter Temp9am: "))
Temp_3pm = float(input("Enter Temp3pm: "))
humidity_9am = float(input("Enter Humidity9am: "))
humidity_3pm = float(input("Enter Humidity3pm: "))

# Get additional input for remaining features
additional_input = {}
for feature in remaining_features:
    additional_input[feature] = default_values[feature]

prediction = predict_rain(location, Temp_9am, Temp_3pm, humidity_9am, humidity_3pm, **additional_input)
print("Prediction of Rain Tomorrow:", prediction)


Enter Location:  Albury
Enter Temp9am:  13.4
Enter Temp3pm:  22.9
Enter Humidity9am:  71
Enter Humidity3pm:  22


Shape of input data after preprocessing: (1, 19)
Prediction of Rain Tomorrow: 1.0
